server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8