server:
  port: 8080
spring:
  redis:
    host: r-bp1rllgi5gyrapnynp.redis.rds.aliyuncs.com
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8