---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/2 1:19 AM
---

local activeSetKey = KEYS[1]
local readySetKey = KEYS[2]
local ticketToken = ARGV[1]
local ticketId = ARGV[2]
local queueId = ARGV[3]
local ticketAuthCode = ARGV[4]

local response = {}

local realAuthCode = redis.call("hget", ticketId, "authCode")
if ticketAuthCode ~= realAuthCode then
    response[1] = 40101
    return response
end

local isTicketActivated = redis.call("zscore", activeSetKey, ticketToken)
if isTicketActivated then
    response[1] = 40004
    return response
end

local isReadyToActivate = redis.call("zscore", readySetKey, ticketId)
if not isReadyToActivate then
    response[1] = 41202
    return response
end

local expireTime = redis.call("hget", queueId, "permissionExpirationSeconds")

redis.call("zadd", activeSetKey, expireTime, ticketToken)
redis.call("zrem", readySetKey, ticketId)

response[1] = 200
return response