---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/2 1:19 AM
---

local activeSetKey = KEYS[1]
local readySetKey = KEYS[2]
local ticketToken = ARGV[1]
local ticketId = ARGV[2]
local queueId = ARGV[3]
local ticketAuthCode = ARGV[4]
local current_time = tonumber(ARGV[5])

local realAuthCode = redis.call("hget", ticketId, "authCode")
if ticketAuthCode ~= realAuthCode then
    return 40101
end

local isTicketActivated = redis.call("zscore", activeSetKey, ticketToken)
if isTicketActivated then
    return 40004
end

local isReadyToActivate = redis.call("zscore", readySetKey, ticketId)
if not isReadyToActivate then
    return 41202
end

local expireTime = redis.call("hget", queueId, "permissionExpirationSeconds")

redis.call("zadd", activeSetKey, current_time + expireTime, ticketToken)
redis.call("zrem", readySetKey, ticketId)

return 200