---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/26 5:52 PM
---

local current_time = tonumber(ARGV[1])

local all_queues = redis.call("smembers", "queues")

for i, queue_id in ipairs(all_queues) do
    local activeSet = "set:active:" .. queue_id
    local readySet = "set:ready:" .. queue_id
    redis.call("zremrangebyscore", activeSet, 0, current_time)
    redis.call("zremrangebyscore", readySet, 0, current_time)

    local active_user = redis.call("zcard", activeSet)
    local ready_user = redis.call("zcard", readySet)

    local max_active_users = tonumber(redis.call("hget", queue_id, "maxActiveUsers"))
    local head = tonumber(redis.call("hget", queue_id, "head"))
    local tail = tonumber(redis.call("hget", queue_id, "tail"))
    local timeout = tonumber(redis.call("hget", queue_id, "timeoutForActivateSeconds"))

    local new_ready_user = math.min(max_active_users - active_user - ready_user, tail - head)

    for position = head + 1, head + new_ready_user do
        redis.call("zadd", readySet, current_time + timeout, "t:" .. queue_id .. ":" .. position)
    end

    redis.call("hset", queue_id, "head", head + new_ready_user)
end
