---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/2 1:19 AM
---

local activeSetKey = KEYS[1]
local readySetKey = KEYS[2]
local ticketToken = ARGV[1]
local ticketId = ARGV[2]
local ticketAuthCode = ARGV[3]

local result = 200

local realAuthCode = redis.call("hget", ticketId, "authCode")
if ticketAuthCode ~= realAuthCode then
    result = 40101
end

local response = {}
response[1] = result

if result ~= 200 then
    return response
end

redis.call("zrem", activeSetKey, ticketToken)
redis.call("zrem", readySetKey, ticketToken)
redis.call("del", ticketId)

return response