---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/1 9:12 AM
---

local activeSetKey = KEYS[1]
local ticketToken = ARGV[1]
local ticketId = ARGV[2]

local result = 200

local isTicketActivated = redis.call("zscore", activeSetKey, ticketToken)

if not isTicketActivated then
    result = 41201
else
    local isTicketOccupied = redis.call("hget", ticketId, "occupied")
    if isTicketOccupied then
        result = 40901
    end
end

local response = {}
response[1] = result
return response

