---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jingchen.
--- DateTime: 2020/7/19 11:48 AM
---

redis.call("hset", "q:unitest", "id", "q:unitest", "name", "testqueue", "capacity", "10000", "head", "0", "tail", "0", "maxActiveUsers", "1000", "permissionExpirationSeconds", "300", "timeoutForActivateSeconds", "20", "callbackURL", "openqueue.io")